// Ver.150: personal one-time task reminders surfaced in Today view.
(function installRemindersV150(){
  const W=window.WorkBoardWorkflowV150||window.WorkBoardWorkflowV149||window.WorkBoardWorkflowV148;if(!W)return;
  let scheduled=false,lastUser=W.currentUser?.()||'',notified=new Set(),clearing=new Set();
  const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'})[c]);
  function detailId(detail){const key=detail?.querySelector?.('[data-action="delete"]')?.dataset?.operationKey||'';return key.startsWith('task-delete:')?key.slice(12):''}
  function inputValue(ms){if(!ms)return'';const d=new Date(ms),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
  function formatAt(ms){const d=new Date(ms),now=new Date(),p=n=>String(n).padStart(2,'0');const same=d.toDateString()===now.toDateString();return`${same?'今日':`${d.getMonth()+1}/${d.getDate()}`} ${p(d.getHours())}:${p(d.getMinutes())}`}
  function openTask(id){if(typeof window.selectTask==='function'){window.selectTask(String(id));return}const task=W.taskMap().get(String(id)),q=document.getElementById('searchInput');if(task&&q){q.value=task.title||'';q.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('[data-task-layout="list"]')?.click();setTimeout(()=>document.querySelector(`[data-task-id="${CSS.escape(String(id))}"]`)?.click(),80)}}
  async function clearCompleted(){const map=W.taskMap(),items=W.remindersFor?.()||{};for(const [id] of Object.entries(items)){const task=map.get(id);if(task&&W.isCompleted(task)&&!clearing.has(id)){clearing.add(id);try{await W.writeReminder(id,null)}finally{clearing.delete(id)}}}}
  function reminderState(item){if(!item)return['未設定','is-none'];const diff=Number(item.at)-Date.now();if(diff<=0)return['🔔 確認時刻','is-due'];if(diff<=86400000)return[formatAt(item.at),'is-soon'];return[formatAt(item.at),'is-future']}
  function patchDetail(){
    const detail=document.getElementById('detailBody');if(!detail||detail.classList.contains('empty'))return;const id=detailId(detail),task=W.taskMap().get(id);if(!task)return;const item=W.reminderFor?.(id)||null,[label,klass]=reminderState(item),sig=`${id}|${item?.at||0}|${item?.note||''}|${W.currentUser?.()||''}`;let section=detail.querySelector('.workflow-reminder-v150');if(section?.dataset.signature===sig)return;if(section)section.remove();
    section=document.createElement('section');section.className='detail-section workflow-reminder-v150';section.dataset.signature=sig;
    if(W.isCompleted(task)){section.innerHTML='<div class="workflow-reminder-head-v150"><div><h4>確認リマインダー</h4><p>完了済みタスクにはリマインダーを設定しません。</p></div></div>'}
    else section.innerHTML=`<div class="workflow-reminder-head-v150"><div><h4>確認リマインダー</h4><p>期限とは別に、自分だけの「あとで確認」を設定できます。</p></div><span class="workflow-reminder-state-v150 ${klass}">${esc(label)}</span></div><div class="workflow-reminder-form-v150"><label><span>再確認日時</span><input type="datetime-local" data-reminder-at-v150 value="${esc(inputValue(item?.at||0))}"></label><label><span>メモ（任意）</span><input type="text" maxlength="120" data-reminder-note-v150 value="${esc(item?.note||'')}" placeholder="例：業者からの回答を確認"></label><div class="workflow-reminder-actions-v150"><button type="button" class="primary-button" data-save-reminder-v150>保存</button>${item?'<button type="button" class="ghost-button" data-clear-reminder-v150>解除</button>':''}</div></div>`;
    const panel=detail.querySelector('.task-detail-panel-v149[data-tab-panel="details"]')||detail,anchor=panel.querySelector('.workflow-relations-v150')||panel.querySelector('.workflow-dependencies-v149')||panel.querySelector('.detail-section');anchor?anchor.insertAdjacentElement('afterend',section):panel.appendChild(section);
    section.querySelector('[data-save-reminder-v150]')?.addEventListener('click',async()=>{const raw=section.querySelector('[data-reminder-at-v150]')?.value||'',at=new Date(raw).getTime(),note=section.querySelector('[data-reminder-note-v150]')?.value.trim()||'';if(!raw||!Number.isFinite(at))return W.notify('再確認日時を入力してください。',true);if(at<=Date.now()+30000)return W.notify('現在より後の日時を設定してください。',true);const r=await W.writeReminder(id,{at,note});if(r?.ok){notified.delete(`${id}:${at}`);W.notify('確認リマインダーを設定しました。')}});
    section.querySelector('[data-clear-reminder-v150]')?.addEventListener('click',async()=>{const r=await W.writeReminder(id,null);if(r?.ok)W.notify('確認リマインダーを解除しました。')});
  }
  function dueItems(){const map=W.taskMap(),items=W.remindersFor?.()||{},end=new Date();end.setHours(23,59,59,999);return Object.entries(items).map(([id,item])=>({id,item,task:map.get(id)})).filter(x=>x.task&&!W.isCompleted(x.task)&&Number(x.item.at)<=end.getTime()).sort((a,b)=>Number(a.item.at)-Number(b.item.at))}
  function patchToday(){
    const root=document.getElementById('todayView');if(!root||root.hidden)return;root.querySelector('.today-reminders-v150')?.remove();const items=dueItems();if(!items.length)return;
    const section=document.createElement('section');section.className='today-reminders-v150';section.innerHTML=`<div class="today-reminders-head-v150"><div><span>PERSONAL REMINDER</span><h4>確認リマインダー</h4></div><strong>${items.length}件</strong></div><div class="today-reminder-list-v150">${items.slice(0,6).map(({id,item,task})=>`<article class="today-reminder-item-v150 ${Number(item.at)<=Date.now()?'is-due':''}"><button type="button" data-open-reminder-v150="${esc(id)}"><strong>${esc(task.title||'名称未設定')}</strong><span>${esc(item.note||'再確認する')}</span></button><div><time>${esc(formatAt(item.at))}</time><button type="button" class="ghost-button" data-clear-today-reminder-v150="${esc(id)}">確認済み</button></div></article>`).join('')}</div>`;
    const anchor=root.querySelector('.today-head-after-activity');anchor?anchor.insertAdjacentElement('afterend',section):root.prepend(section);
    section.querySelectorAll('[data-open-reminder-v150]').forEach(b=>b.addEventListener('click',()=>openTask(b.dataset.openReminderV150)));
    section.querySelectorAll('[data-clear-today-reminder-v150]').forEach(b=>b.addEventListener('click',async()=>{const r=await W.writeReminder(b.dataset.clearTodayReminderV150,null);if(r?.ok)W.notify('リマインダーを確認済みにしました。')}));
  }
  function notifyDue(){const now=Date.now(),map=W.taskMap();for(const [id,item] of Object.entries(W.remindersFor?.()||{})){const task=map.get(id);if(!task||W.isCompleted(task)||Number(item.at)>now)continue;const key=`${id}:${item.at}`;if(notified.has(key))continue;notified.add(key);W.notify(`🔔 ${task.title}${item.note?`：${item.note}`:''}`);try{if('Notification'in window&&Notification.permission==='granted')new Notification(`確認リマインダー：${task.title}`,{body:item.note||'確認時刻になりました。'})}catch(_){}}}
  function patch(){const user=W.currentUser?.()||'';if(user!==lastUser){lastUser=user;notified=new Set()}clearCompleted();patchDetail();patchToday();notifyDue()}
  function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;patch()})}
  window.addEventListener('workflow-v150-update',schedule);window.addEventListener('workflow-v149-update',schedule);
  new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length||x.removedNodes.length||x.type==='characterData'))schedule()}).observe(document.getElementById('mainContent')||document.body,{childList:true,subtree:true,characterData:true});
  setInterval(schedule,30000);patch();
})();
